version: '3'

services:
  api:
    image: node:fermium-alpine
    container_name: api
    command: npm run start:dev
    depends_on:
      - mongodb
      - redis
    ports:
      - "9229:9229"
      - "3000:3000"
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - container_environment

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - container_environment

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - container_environment

networks:
  container_environment: